project:
  type: website
  output-dir: "docs"


website:
  page-navigation: true
  title: ""
  description: ""

  navbar:
    background: "#A7D5E8"
    align: center
    title: false
    collapse-below: lg
 
    left:
      - text: "Overview"
        href: index.qmd
      - text: "IGH"
        href: IGH.qmd
      - text: "IGL"
        href: IGL.qmd
      - text: "IGK"
        href: IGK.qmd
        
  sidebar:
      
      - id: Overview
        title: "Overview"
        contents:
          - href: index.qmd
          - genotype.qmd

      - id: IGH
        title: "IGH"
        contents:
          - href: IGH.qmd
          - section: "IGHV"
            contents:
              - section: "IGHV1"
                contents:
                - href: IGHV1-ISRF.qmd
              - section: "IGHV4"
                contents:
                - href: IGHV4-EITI.qmd
          - section: "IGHD"
          - section: "IGHJ"

      - id: IGL
        title: "IGL"
        contents:
          - href: IGL.qmd
          - section: "IGLV"
          - section: "IGLJ"

      - id: IGK
        title: "IGK"
        contents:
          - href: IGK.qmd
          - section: "IGKV"
          - section: "IGKJ"

format:
  html:
    theme: [Journal]
    css: [style.css, index.css]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px

freeze: auto

editor: visual