project:
  type: website
  output-dir: "docs"


website:
  page-navigation: true
  title: ""
  description: ""

  navbar:
    background: "#A7D5E8"
    align: center
    title: false
    collapse-below: lg
 
    left:
      - text: "Overview"
        href: index.qmd
      - text: "IGH"
        href: IGH.qmd
      - text: "IGL"
        href: IGL.qmd
      - text: "IGK"
        href: IGK.qmd
        
  sidebar:
      
      - id: Overview
        title: "Overview"
        contents:
          - href: index.qmd
          - genotype.qmd

      - id: IGH
        title: "IGH"
        contents:
          - href: IGH.qmd
          - section: "IGHV"
            contents:
              - section: "IGHV1"
                contents:
                  - href: IGHV1-57IM.qmd
                  - href: IGHV1-BEKE.qmd
                  - href: IGHV1-BSGF.qmd
                  - href: IGHV1-DAVK.qmd
                  - href: IGHV1-FO6G.qmd
                  - href: IGHV1-I24O.qmd
                  - href: IGHV1-ISRF.qmd
                  - href: IGHV1-JHF7.qmd
                  - href: IGHV1-JIGE.qmd
                  - href: IGHV1-RO6H.qmd
                  - href: IGHV1-TNJW.qmd
                  - href: IGHV1-VCNV.qmd
                  - href: IGHV1-Y4Q6.qmd
                  - href: IGHV1-Y7SR.qmd
                  - href: IGHV1-ZGGJ.qmd
              - section: "IGHV2"
                contents:
                  - href: IGHV2-4QUM.qmd
                  - href: IGHV2-5VX5.qmd
                  - href: IGHV2-D2TO.qmd
                  - href: IGHV2-DCLT.qmd
                  - href: IGHV2-DPJA.qmd
                  - href: IGHV2-V7ET.qmd
                  - href: IGHV2-X7EJ.qmd
              - section: "IGHV3"
                contents:
                  - href: IGHV3-2K4H.qmd
                  - href: IGHV3-37F2.qmd
                  - href: IGHV3-4GAP.qmd
                  - href: IGHV3-4PJH.qmd
                  - href: IGHV3-4RPY.qmd
                  - href: IGHV3-4TKM.qmd
                  - href: IGHV3-756H.qmd
                  - href: IGHV3-7HCW.qmd
                  - href: IGHV3-A7N6.qmd
                  - href: IGHV3-B5E7.qmd
                  - href: IGHV3-BKKC.qmd
                  - href: IGHV3-BZMP.qmd
                  - href: IGHV3-C4HU.qmd
                  - href: IGHV3-DCTO.qmd
                  - href: IGHV3-DY3H.qmd
                  - href: IGHV3-E6ZX.qmd
                  - href: IGHV3-GYPG.qmd
                  - href: IGHV3-HFYN.qmd
                  - href: IGHV3-I3JG.qmd
                  - href: IGHV3-JRTS.qmd
                  - href: IGHV3-JU2I.qmd
                  - href: IGHV3-L7BK.qmd
                  - href: IGHV3-LT3H.qmd
                  - href: IGHV3-MCXM.qmd
                  - href: IGHV3-MEBQ.qmd
                  - href: IGHV3-MGEX.qmd
                  - href: IGHV3-N72G.qmd
                  - href: IGHV3-NL4W.qmd
                  - href: IGHV3-O76Z.qmd
                  - href: IGHV3-OLUF.qmd
                  - href: IGHV3-PHO7.qmd
                  - href: IGHV3-PJYR.qmd
                  - href: IGHV3-PRG6.qmd
                  - href: IGHV3-PTFK.qmd
                  - href: IGHV3-R7MJ.qmd
                  - href: IGHV3-RRYX.qmd
                  - href: IGHV3-RSQ5.qmd
                  - href: IGHV3-SOZS.qmd
                  - href: IGHV3-WOIZ.qmd
                  - href: IGHV3-WPIB.qmd
                  - href: IGHV3-X5LH.qmd
                  - href: IGHV3-XVTV.qmd
                  - href: IGHV3-ZJGS.qmd
              - section: "IGHV4"
                contents:
                  - href: IGHV4-2QEK.qmd
                  - href: IGHV4-4GQY.qmd
                  - href: IGHV4-4M7V.qmd
                  - href: IGHV4-4MLZ.qmd
                  - href: IGHV4-4NGE.qmd
                  - href: IGHV4-4V2C.qmd
                  - href: IGHV4-5ARF.qmd
                  - href: IGHV4-5WKJ.qmd
                  - href: IGHV4-64DR.qmd
                  - href: IGHV4-6KBL.qmd
                  - href: IGHV4-6LZZ.qmd
                  - href: IGHV4-7BJU.qmd
                  - href: IGHV4-7PM2.qmd
                  - href: IGHV4-MYX4.qmd
                  - href: IGHV4-7UKP.qmd
                  - href: IGHV4-AATP.qmd
                  - href: IGHV4-AMYK.qmd
                  - href: IGHV4-BQLH.qmd
                  - href: IGHV4-CCOK.qmd
                  - href: IGHV4-DJPP.qmd
                  - href: IGHV4-JA6D.qmd
                  - href: IGHV4-DXH5.qmd
                  - href: IGHV4-E2ZN.qmd
                  - href: IGHV4-EAIX.qmd
                  - href: IGHV4-EITI.qmd
                  - href: IGHV4-FAZN.qmd
                  - href: IGHV4-HDAZ.qmd
                  - href: IGHV4-HHZI.qmd
                  - href: IGHV4-HNNT.qmd
                  - href: IGHV4-HZTT.qmd
                  - href: IGHV4-I3XU.qmd
                  - href: IGHV4-JJNU.qmd
                  - href: IGHV4-Y4BX.qmd
                  - href: IGHV4-JZNW.qmd
                  - href: IGHV4-KG56.qmd
                  - href: IGHV4-MLR2.qmd
                  - href: IGHV4-N2SB.qmd
                  - href: IGHV4-NBRY.qmd
                  - href: IGHV4-NFRM.qmd
                  - href: IGHV4-NZ7A.qmd
                  - href: IGHV4-PY3X.qmd
                  - href: IGHV4-R3YH.qmd
                  - href: IGHV4-U2RC.qmd
                  - href: IGHV4-U675.qmd
                  - href: IGHV4-V7V4.qmd
                  - href: IGHV4-VX5Q.qmd
                  - href: IGHV4-XTDW.qmd
                  - href: IGHV4-Y4FC.qmd
                  - href: IGHV4-YE26.qmd
                  - href: IGHV4-ZNL3.qmd
              - section: "IGHV5"
                contents:
                  - href: IGHV5-2DZZ.qmd
                  - href: IGHV5-2GFF.qmd
                  - href: IGHV5-D2NK.qmd
                  - href: IGHV5-T2J5.qmd
              - section: "IGHV6"
                contents:
                  - href: IGHV6-UXXO.qmd
              - section: "IGHV7"
                contents:
                  - href: IGHV7-75KG.qmd
                  - href: IGHV7-S2SK.qmd
              - section: "IGHV8"
                contents:
                  - href: IGHV8-4KLO.qmd
                  - href: IGHV8-4SV6.qmd
                  - href: IGHV8-4WHC.qmd
                  - href: IGHV8-65SO.qmd
                  - href: IGHV8-6R7J.qmd
                  - href: IGHV8-6TUE.qmd
                  - href: IGHV8-AHTF.qmd
                  - href: IGHV8-DH64.qmd
                  - href: IGHV8-GESA.qmd
                  - href: IGHV8-GKLX.qmd
                  - href: IGHV8-MBLR.qmd
                  - href: IGHV8-NEPN.qmd
                  - href: IGHV8-PWAC.qmd
                  - href: IGHV8-QBAS.qmd
                  - href: IGHV8-RZNS.qmd
                  - href: IGHV8-WAVT.qmd
                  - href: IGHV8-YMST.qmd
          - section: "IGHD"
            contents:
              - section: "IGHD1"
                contents:
                  - href: IGHD1-2J4B.qmd
                  - href: IGHD1-BAAI.qmd
                  - href: IGHD1-GRMY.qmd
                  - href: IGHD1-QQWR.qmd
                  - href: IGHD1-RIPD.qmd
              - section: "IGHD3"
                contents:
                  - href: IGHD3-X76R.qmd
              - section: "IGHD4"
                contents:
                  - href: IGHD4-NW5N.qmd
              - section: "IGHD7"
                contents:
                  - href: IGHD7-7HR7.qmd
                  - href: IGHD7-C7RJ.qmd
              - section: "IGHD8"
                contents:
                  - href: IGHD8-SXKU.qmd
              - section: "IGHD9"
                contents:
                  - href: IGHD9-64ZP.qmd
                  - href: IGHD9-DWON.qmd
                  - href: IGHD9-LDSS.qmd
                  - href: IGHD9-T3KD.qmd
              - section: "IGHD11"
                contents:
                  - href: IGHD11-B3VX.qmd
              - section: "IGHD14"
                contents:
                  - href: IGHD14-5Q35.qmd
                  - href: IGHD14-ANVS.qmd
              - section: "IGHD18"
                contents:
                  - href: IGHD18-75EJ.qmd
              - section: "IGHD19"
                contents:
                  - href: IGHD19-GADR.qmd
              - section: "IGHD20"
                contents:
                  - href: IGHD20-72Z4.qmd
                  - href: IGHD20-VBVC.qmd
              - section: "IGHD21"
                contents:
                  - href: IGHD21-B4TS.qmd
                  - href: IGHD21-ELDI.qmd
                  - href: IGHD21-JYXZ.qmd
                  - href: IGHD21-QKRU.qmd
              - section: "IGHD22"
                contents:
                  - href: IGHD22-AWN2.qmd
                  - href: IGHD22-ZLQB.qmd
              - section: "IGHD23"
                contents:
                  - href: IGHD23-PSVV.qmd
              - section: "IGHD24"
                contents:
                  - href: IGHD24-HJME.qmd
          - section: "IGHJ"
            contents:
              - section: "IGHJ1"
                contents:
                  - href: IGHJ1-PVVP.qmd
              - section: "IGHJ2"
                contents:
                  - href: IGHJ2-DDLH.qmd
              - section: "IGHJ3"
                contents:
                  - href: IGHJ3-XRNC.qmd
              - section: "IGHJ4"
                contents:
                  - href: IGHJ4-JSJ6.qmd
              - section: "IGHJ5"
                contents:
                  - href: IGHJ5-MIQL.qmd
                  - href: IGHJ5-XD6S.qmd
              - section: "IGHJ6"
                contents:
                  - href: IGHJ6-GAIV.qmd


      - id: IGL
        title: "IGL"
        contents:
          - href: IGL.qmd
          - section: "IGLV"
          - section: "IGLJ"

      - id: IGK
        title: "IGK"
        contents:
          - href: IGK.qmd
          - section: "IGKV"
          - section: "IGKJ"

format:
  html:
    theme: [Journal]
    css: [style.css, index.css]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px

freeze: auto

editor: visual